/**
 * Seeded DEMO catalog.
 *
 * MOCK INTEGRITY: every partner identity below is fictional and explicitly
 * neutral. No real Iranian institution, product, rate or availability is
 * represented here. Real institutions may replace these only when verified
 * data or agreements exist.
 */

import type { Partner, Product } from "./types";
import { millionToman } from "@/lib/money";

const ASOF = "2026-07-24T09:00:00.000Z";

export const PARTNERS: Partner[] = [
  { id: "p_aban", name: "مؤسسه اعتباری آبان (نمونه)", kind: "credit_institution", demo: true },
  { id: "p_karan", name: "بانک نمونهٔ کاران", kind: "bank", demo: true },
  { id: "p_sepehrad", name: "صندوق سپهراد (نمونه)", kind: "fund", demo: true },
  { id: "p_rahvar", name: "لیزینگ رهوار (نمونه)", kind: "leasing", demo: true },
  { id: "p_tadbir", name: "فین‌تک تدبیر (نمونه)", kind: "fintech", demo: true },
];

export const partnerById = (id: string): Partner =>
  PARTNERS.find((p) => p.id === id) ?? PARTNERS[0];

export const PRODUCTS: Product[] = [
  {
    id: "pr_business_growth",
    partnerId: "p_aban",
    name: "تسهیلات رشد کسب‌وکار",
    ratePercent: 23,
    maxTermMonths: 60,
    typicalDays: 12,
    asOf: ASOF,
    notes: "برای دارندگان جواز کسب با گردش حساب پایدار.",
    rules: {
      minAmount: millionToman(100),
      maxAmount: millionToman(2000),
      allowedEmployment: ["business_owner", "self_employed", "salaried"],
      requiresCollateral: null,
      requiresGuarantor: ["business", "payroll"],
      minIncomeBand: "20_50",
      maxDebtLoad: "light",
      allowedPurposes: ["business", "debt", "personal"],
    },
  },
  {
    id: "pr_business_micro",
    partnerId: "p_sepehrad",
    name: "خرد کسب‌وکار بدون ضامن",
    ratePercent: 18,
    maxTermMonths: 36,
    typicalDays: 21,
    asOf: ASOF,
    notes: "بدون نیاز به ضامن، سقف محدودتر، بررسی گردش حساب شش‌ماهه.",
    rules: {
      minAmount: millionToman(30),
      maxAmount: millionToman(400),
      allowedEmployment: ["business_owner", "self_employed"],
      requiresCollateral: null,
      requiresGuarantor: null,
      minIncomeBand: "under_20",
      maxDebtLoad: "light",
      allowedPurposes: ["business", "personal", "debt"],
    },
  },
  {
    id: "pr_collateral_line",
    partnerId: "p_karan",
    name: "خط اعتباری با وثیقه ملکی",
    ratePercent: 21,
    maxTermMonths: 84,
    typicalDays: 30,
    asOf: ASOF,
    notes: "سقف بالا، مشروط به وثیقهٔ ملکی قابل ترهین.",
    rules: {
      minAmount: millionToman(300),
      maxAmount: millionToman(5000),
      allowedEmployment: ["business_owner", "self_employed", "salaried", "retired"],
      requiresCollateral: ["property"],
      requiresGuarantor: null,
      minIncomeBand: "20_50",
      maxDebtLoad: "heavy",
      allowedPurposes: ["business", "home", "debt", "personal", "education"],
    },
  },
  {
    id: "pr_payroll_personal",
    partnerId: "p_karan",
    name: "وام حقوق‌بگیران",
    ratePercent: 19,
    maxTermMonths: 48,
    typicalDays: 10,
    asOf: ASOF,
    notes: "ویژهٔ حقوق‌بگیران با کسر از حقوق و یک ضامن کارمند.",
    rules: {
      minAmount: millionToman(20),
      maxAmount: millionToman(300),
      allowedEmployment: ["salaried"],
      requiresCollateral: null,
      requiresGuarantor: ["payroll"],
      minIncomeBand: "under_20",
      maxDebtLoad: "light",
      allowedPurposes: ["personal", "marriage", "education", "debt", "car"],
    },
  },
  {
    id: "pr_fast_cash",
    partnerId: "p_tadbir",
    name: "اعتبار سریع دیجیتال",
    ratePercent: 27,
    maxTermMonths: 18,
    typicalDays: 2,
    asOf: ASOF,
    notes: "پرداخت سریع، مبلغ محدود، بدون ضامن و وثیقه.",
    rules: {
      minAmount: millionToman(5),
      maxAmount: millionToman(120),
      allowedEmployment: [
        "salaried",
        "self_employed",
        "business_owner",
        "retired",
        "student",
      ],
      requiresCollateral: null,
      requiresGuarantor: null,
      minIncomeBand: "under_20",
      maxDebtLoad: "light",
      allowedPurposes: ["personal", "debt", "education", "marriage", "business"],
    },
  },
  {
    id: "pr_home_purchase",
    partnerId: "p_karan",
    name: "تسهیلات خرید مسکن",
    ratePercent: 20,
    maxTermMonths: 120,
    typicalDays: 45,
    asOf: ASOF,
    notes: "مختص خرید مسکن، نیاز به وثیقه یا ملک در رهن.",
    rules: {
      minAmount: millionToman(500),
      maxAmount: millionToman(4000),
      allowedEmployment: ["salaried", "business_owner", "self_employed"],
      requiresCollateral: ["property"],
      requiresGuarantor: null,
      minIncomeBand: "50_100",
      maxDebtLoad: "light",
      allowedPurposes: ["home"],
    },
  },
  {
    id: "pr_car_lease",
    partnerId: "p_rahvar",
    name: "لیزینگ خودرو",
    ratePercent: 25,
    maxTermMonths: 48,
    typicalDays: 7,
    asOf: ASOF,
    notes: "خودرو تا زمان تسویه در وثیقه باقی می‌ماند.",
    rules: {
      minAmount: millionToman(200),
      maxAmount: millionToman(1500),
      allowedEmployment: ["salaried", "self_employed", "business_owner"],
      requiresCollateral: ["vehicle", "property"],
      requiresGuarantor: null,
      minIncomeBand: "20_50",
      maxDebtLoad: "light",
      allowedPurposes: ["car"],
    },
  },
  {
    id: "pr_deposit_backed",
    partnerId: "p_aban",
    name: "تسهیلات در قبال سپرده",
    ratePercent: 15,
    maxTermMonths: 36,
    typicalDays: 3,
    asOf: ASOF,
    notes: "کمترین نرخ، مشروط به سپردهٔ مسدودشده نزد همان مؤسسه.",
    rules: {
      minAmount: millionToman(20),
      maxAmount: millionToman(1000),
      allowedEmployment: [
        "salaried",
        "self_employed",
        "business_owner",
        "retired",
        "student",
        "unemployed",
      ],
      requiresCollateral: ["deposit"],
      requiresGuarantor: null,
      minIncomeBand: "under_20",
      maxDebtLoad: "heavy",
      allowedPurposes: [
        "personal",
        "business",
        "debt",
        "education",
        "marriage",
        "car",
        "home",
      ],
    },
  },
  {
    id: "pr_education",
    partnerId: "p_sepehrad",
    name: "وام تحصیلی",
    ratePercent: 12,
    maxTermMonths: 60,
    typicalDays: 25,
    asOf: ASOF,
    notes: "ویژهٔ دانشجویان، با ضامن کارمند.",
    rules: {
      minAmount: millionToman(10),
      maxAmount: millionToman(150),
      allowedEmployment: ["student", "salaried"],
      requiresCollateral: null,
      requiresGuarantor: ["payroll"],
      minIncomeBand: "under_20",
      maxDebtLoad: "light",
      allowedPurposes: ["education"],
    },
  },
  {
    id: "pr_marriage",
    partnerId: "p_sepehrad",
    name: "تسهیلات ازدواج",
    ratePercent: 4,
    maxTermMonths: 84,
    typicalDays: 40,
    asOf: ASOF,
    notes: "نرخ بسیار پایین، صف انتظار طولانی، نیاز به دو ضامن.",
    rules: {
      minAmount: millionToman(100),
      maxAmount: millionToman(400),
      allowedEmployment: ["salaried", "self_employed", "business_owner", "student"],
      requiresCollateral: null,
      requiresGuarantor: ["payroll", "business"],
      minIncomeBand: "under_20",
      maxDebtLoad: "light",
      allowedPurposes: ["marriage"],
    },
  },
  {
    id: "pr_debt_consolidation",
    partnerId: "p_tadbir",
    name: "تجمیع بدهی",
    ratePercent: 24,
    maxTermMonths: 60,
    typicalDays: 14,
    asOf: ASOF,
    notes: "برای تجمیع اقساط پراکنده، مشروط به سابقهٔ پرداخت قابل قبول.",
    rules: {
      minAmount: millionToman(50),
      maxAmount: millionToman(800),
      allowedEmployment: ["salaried", "self_employed", "business_owner"],
      requiresCollateral: null,
      requiresGuarantor: ["payroll", "business"],
      minIncomeBand: "20_50",
      maxDebtLoad: "heavy",
      allowedPurposes: ["debt", "personal"],
    },
  },
];
