/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as HandoffHandoffIdRouteImport } from './routes/handoff.$handoffId'
import { Route as OpportunityProductIdRouteImport } from './routes/opportunity.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffHandoffIdRoute = HandoffHandoffIdRouteImport.update({
  id: '/handoff/$handoffId',
  path: '/handoff/$handoffId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityProductIdRoute = OpportunityProductIdRouteImport.update({
  id: '/opportunity/$productId',
  path: '/opportunity/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credit': typeof CreditRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/readiness': typeof ReadinessRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credit': typeof CreditRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/readiness': typeof ReadinessRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credit': typeof CreditRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/readiness': typeof ReadinessRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credit'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/radar'
    | '/readiness'
    | '/handoff/$handoffId'
    | '/opportunity/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credit'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/radar'
    | '/readiness'
    | '/handoff/$handoffId'
    | '/opportunity/$productId'
  id:
    | '__root__'
    | '/'
    | '/credit'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/radar'
    | '/readiness'
    | '/handoff/$handoffId'
    | '/opportunity/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditRoute: typeof CreditRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  RadarRoute: typeof RadarRoute
  ReadinessRoute: typeof ReadinessRoute
  HandoffHandoffIdRoute: typeof HandoffHandoffIdRoute
  OpportunityProductIdRoute: typeof OpportunityProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$handoffId': {
      id: '/handoff/$handoffId'
      path: '/handoff/$handoffId'
      fullPath: '/handoff/$handoffId'
      preLoaderRoute: typeof HandoffHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$productId': {
      id: '/opportunity/$productId'
      path: '/opportunity/$productId'
      fullPath: '/opportunity/$productId'
      preLoaderRoute: typeof OpportunityProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditRoute: CreditRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  RadarRoute: RadarRoute,
  ReadinessRoute: ReadinessRoute,
  HandoffHandoffIdRoute: HandoffHandoffIdRoute,
  OpportunityProductIdRoute: OpportunityProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
