/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityProductIdRouteImport } from './routes/opportunity.$productId'

const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityProductIdRoute = OpportunityProductIdRouteImport.update({
  id: '/opportunity/$productId',
  path: '/opportunity/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/radar': typeof RadarRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/radar': typeof RadarRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRoute
  '/radar': typeof RadarRoute
  '/opportunity/$productId': typeof OpportunityProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opportunities' | '/radar' | '/opportunity/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opportunities' | '/radar' | '/opportunity/$productId'
  id: '__root__' | '/' | '/opportunities' | '/radar' | '/opportunity/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RadarRoute: typeof RadarRoute
  OpportunityProductIdRoute: typeof OpportunityProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$productId': {
      id: '/opportunity/$productId'
      path: '/opportunity/$productId'
      fullPath: '/opportunity/$productId'
      preLoaderRoute: typeof OpportunityProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RadarRoute: RadarRoute,
  OpportunityProductIdRoute: OpportunityProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
